// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package launcher

import (
	"github.com/leiqD/go-socket5/infrastructure/conf"
	"github.com/leiqD/go-socket5/infrastructure/datastore"
	"github.com/leiqD/go-socket5/infrastructure/logger"
	"github.com/leiqD/go-socket5/infrastructure/router"
	"github.com/leiqD/go-socket5/interface/controller"
	"github.com/leiqD/go-socket5/trans"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeConfig(cfgPath string) *conf.Configs {
	viper := conf.NewViper(cfgPath)
	configs := conf.NewConfig(viper)
	return configs
}

func InitializeLog(cfg logger.LoggerConfig) *logger.Zap {
	zap := logger.NewLogger(cfg)
	return zap
}

func InitialDataStore(cfg datastore.MYSQLconfig) (*gorm.DB, error) {
	db, err := datastore.NewMYSQLDB(cfg)
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitialRouter(cfg router.RouterConfig, control controller.AppController) router.Router {
	routerRouter := router.NewRouter(cfg, control)
	return routerRouter
}

func InitialTrans() trans.Trans {
	transTrans := trans.NetTrans()
	return transTrans
}
